[build]
  command = "npm run build"
  publish = "build_production"
  environment = { PHP_VERSION = "8.0" }

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"