[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "https://msecorp.ca"
  to = "https://modernsign.ca"
  status = 301
  force = true
