[build]
  command = "npm run prod"
  publish = "build_production"
  environment = { PHP_VERSION = "8.1" }

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "https://msecorp.ca"
  to = "https://modernsign.ca"
  status = 301
  force = true